// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzbzObC8yJ2ASlYzrL_Gqyb5tG4jiHzxY',
    appId: '1:328940121783:web:d57d28ae20bbc26bd2e732',
    messagingSenderId: '328940121783',
    projectId: 'hotel-palembang',
    authDomain: 'hotel-palembang.firebaseapp.com',
    databaseURL: 'https://hotel-palembang-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-palembang.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3U57AI5gWjbAybUg1_dQvWKL1UMSNBU',
    appId: '1:328940121783:android:46e33c4510098123d2e732',
    messagingSenderId: '328940121783',
    projectId: 'hotel-palembang',
    databaseURL: 'https://hotel-palembang-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-palembang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPRYtdtnaF5jbmTFoEjzcfmqq8AtIG_e4',
    appId: '1:328940121783:ios:a4cb319115f1b87fd2e732',
    messagingSenderId: '328940121783',
    projectId: 'hotel-palembang',
    databaseURL: 'https://hotel-palembang-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-palembang.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPRYtdtnaF5jbmTFoEjzcfmqq8AtIG_e4',
    appId: '1:328940121783:ios:a4cb319115f1b87fd2e732',
    messagingSenderId: '328940121783',
    projectId: 'hotel-palembang',
    databaseURL: 'https://hotel-palembang-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-palembang.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzbzObC8yJ2ASlYzrL_Gqyb5tG4jiHzxY',
    appId: '1:328940121783:web:779f3b9d9164bd94d2e732',
    messagingSenderId: '328940121783',
    projectId: 'hotel-palembang',
    authDomain: 'hotel-palembang.firebaseapp.com',
    databaseURL: 'https://hotel-palembang-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-palembang.firebasestorage.app',
  );

}